### ISSUE TITLE
Rename operations to their full name(add -> addition, mul -> multiplication)

### ISSUE THREAD

**Issue by AlbertSu123** [paulrberg/prb-math#39] opened 2021-05-30 13:20 UTC
Solidity gives the following warning when a instruction from a contract has the same name as an instruction in solidity's assembly. 

_Warning: Variable is shadowed in inline assembly by an instruction of the same name
--> prb-math/contracts/PRBMathUD60x18.sol:75:5:
75 |     function div(uint256 x, uint256 y) internal pure returns (uint256 result) {
|     ^ (Relevant source part starts here and spans across multiple lines)._

Would you accept a pull request that renames all conflicting operations with their full instruction name?

**Comment by paulrberg** [comment] 2021-05-30 15:53
Closing, duplicate of https://github.com/hifi-finance/prb-math/discussions/35. Let's move the discussion there. 

Can you try bump the version of the Solidity compiler to the latest version (0.8.4) and see if that makes the warnings go away?

**Closed** 2021-05-30 15:53 UTC
Labels: duplicate
